package orchestrator

import (
	"context"
	"log/slog"

	"github.com/opentalon/opentalon/internal/logger"
)

// WorkflowExecutor runs Talon workflow blocks. The Talon language runtime
// implements this interface; the orchestrator calls it when the planner
// detects a multi-step request that benefits from deterministic execution
// (batch operations, pagination, multi-tool chains).
//
// See: https://github.com/opentalon/talon-language/issues/38
type WorkflowExecutor interface {
	// Execute compiles and runs a Talon workflow block. The workflow text
	// is generated by the LLM in a single call. MCP tool calls inside the
	// workflow are routed through the provided MCPCaller.
	//
	// Returns the final result as a human-readable summary and any error.
	Execute(ctx context.Context, workflow string, caller MCPCaller) (*WorkflowResult, error)
}

// MCPCaller routes MCP tool calls from the Talon workflow runtime to the
// orchestrator's plugin system. The orchestrator implements this using
// executeCall().
type MCPCaller interface {
	// CallTool invokes an MCP tool by server and tool name with the given
	// arguments. Returns the structured result or an error.
	CallTool(ctx context.Context, server, tool string, args map[string]any) (map[string]any, error)
}

// WorkflowResult holds the output of a Talon workflow execution.
type WorkflowResult struct {
	// Summary is a human-readable description of what happened, suitable
	// for the LLM to relay to the user.
	Summary string

	// StepResults holds the result of each step, keyed by step name.
	StepResults map[string]any

	// StepsExecuted is the number of steps that ran successfully.
	StepsExecuted int

	// StepsSkipped is the number of steps skipped due to a dependency failure.
	StepsSkipped int

	// Error is set if any step failed. Dependent steps are skipped.
	Error string
}

// executeWorkflow handles the execute_workflow native tool call. It extracts
// the workflow text from the tool arguments and routes it to the Talon runtime.
// If no runtime is registered, it returns an error guiding the LLM to fall
// back to individual tool calls.
func (o *Orchestrator) executeWorkflow(ctx context.Context, call ToolCall) ToolResult {
	workflow := call.Args["workflow"]
	if workflow == "" {
		slog.Warn("workflow: execute_workflow called with empty workflow",
			"call_id", call.ID)
		return ToolResult{
			CallID: call.ID,
			Error:  "workflow argument is required. Provide a Talon workflow block.",
		}
	}

	log := logger.FromContext(ctx)
	log.Info("workflow: execute_workflow called",
		"call_id", call.ID,
		"workflow_len", len(workflow))
	// Log the full generated Talon code at Debug level so /debug shows it.
	log.Debug("workflow: generated talon code",
		"call_id", call.ID,
		"code", workflow)

	// TODO: route to the Talon runtime when available.
	// For now, return an informative error so the LLM falls back to
	// individual tool calls. This allows the tool to be registered and
	// tested before the runtime is ready.
	slog.Warn("workflow: Talon runtime not yet available, workflow not executed",
		"call_id", call.ID)
	return ToolResult{
		CallID: call.ID,
		Error:  "Talon workflow runtime is not yet available. Please use individual tool calls instead (list-items, submit-workorder, etc.).",
	}
}

// isWorkflowCandidate determines whether a planner result should be executed
// by the Talon workflow engine instead of the standard pipeline/agent loop.
//
// Language-agnostic: detection is based on the planner's output, not keywords.
// The planner already understands intent — it returns type "workflow" when it
// detects batch operations, pagination-heavy chains, or multi-step dependencies.
func isWorkflowCandidate(planType string, stepCount int, workflowEnabled bool) bool {
	if !workflowEnabled {
		slog.Debug("workflow: disabled in config")
		return false
	}

	// The planner explicitly flagged this as a workflow.
	if planType == "workflow" {
		slog.Debug("workflow: planner flagged as workflow", "steps", stepCount)
		return true
	}

	// Heuristic fallback: pipelines with many same-shape steps are likely
	// batch operations that benefit from Talon's auto-pagination.
	if stepCount >= 5 {
		slog.Debug("workflow: large pipeline detected as workflow candidate", "steps", stepCount)
		return true
	}

	slog.Debug("workflow: not a candidate", "plan_type", planType, "steps", stepCount)
	return false
}
