package orchestrator

import (
	"context"
	"log/slog"
	"strings"
)

// WorkflowExecutor runs Talon workflow blocks. The Talon language runtime
// implements this interface; the orchestrator calls it when the planner
// detects a multi-step request that benefits from deterministic execution
// (batch operations, pagination, multi-tool chains).
//
// See: https://github.com/opentalon/talon-language/issues/38
type WorkflowExecutor interface {
	// Execute compiles and runs a Talon workflow block. The workflow text
	// is generated by the LLM in a single call. MCP tool calls inside the
	// workflow are routed through the provided MCPCaller.
	//
	// Returns the final result as a human-readable summary and any error.
	Execute(ctx context.Context, workflow string, caller MCPCaller) (*WorkflowResult, error)
}

// MCPCaller routes MCP tool calls from the Talon workflow runtime to the
// orchestrator's plugin system. The orchestrator implements this using
// executeCall().
type MCPCaller interface {
	// CallTool invokes an MCP tool by server and tool name with the given
	// arguments. Returns the structured result or an error.
	CallTool(ctx context.Context, server, tool string, args map[string]any) (map[string]any, error)
}

// WorkflowResult holds the output of a Talon workflow execution.
type WorkflowResult struct {
	// Summary is a human-readable description of what happened, suitable
	// for the LLM to relay to the user.
	Summary string

	// StepResults holds the result of each step, keyed by step name.
	StepResults map[string]any

	// StepsExecuted is the number of steps that ran successfully.
	StepsExecuted int

	// StepsSkipped is the number of steps skipped due to a dependency failure.
	StepsSkipped int

	// Error is set if any step failed. Dependent steps are skipped.
	Error string
}

// workflowKeywords are terms that suggest the user wants a batch/multi-step
// operation better handled by the Talon workflow engine.
var workflowKeywords = []string{
	"all", "every", "batch", "bulk", "mass",
	"alle", "jeden", "jedes", // German
	"todos", "cada", // Spanish
	"tous", "chaque", // French
}

// isWorkflowCandidate determines whether a user request should be handled by
// the Talon workflow engine instead of the standard agent loop. Criteria:
//   - Batch operations: "delete all X", "assign these 50 items"
//   - Pagination-heavy: "list all items matching X" when count > per_page
//   - Multi-step with dependencies: "create blueprint, then 100 twins"
func isWorkflowCandidate(userMessage string, workflowEnabled bool) bool {
	if !workflowEnabled {
		slog.Debug("workflow: disabled in config")
		return false
	}

	lower := strings.ToLower(userMessage)
	for _, kw := range workflowKeywords {
		if strings.Contains(lower, kw) {
			slog.Debug("workflow: candidate detected",
				"keyword", kw,
				"message", userMessage)
			return true
		}
	}

	slog.Debug("workflow: not a candidate", "message", userMessage)
	return false
}
