version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocritic
  settings:
    gocritic:
      enabled-checks:
        - dupImport
        - nestingReduce
        - unnecessaryBlock

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
