// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: channel.proto

package channelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *structpb.Struct       `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigureRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{1}
}

type ToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolDefinition      `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolsResponse) Reset() {
	*x = ToolsResponse{}
	mi := &file_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolsResponse) ProtoMessage() {}

func (x *ToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolsResponse.ProtoReflect.Descriptor instead.
func (*ToolsResponse) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{2}
}

func (x *ToolsResponse) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ToolDefinition struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Plugin            string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Description       string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Action            string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	ActionDescription string                 `protobuf:"bytes,4,opt,name=action_description,json=actionDescription,proto3" json:"action_description,omitempty"`
	Method            string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Url               string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Body              string                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	Headers           map[string]string      `protobuf:"bytes,8,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequiredEnv       []string               `protobuf:"bytes,9,rep,name=required_env,json=requiredEnv,proto3" json:"required_env,omitempty"`
	Parameters        []*ToolParam           `protobuf:"bytes,10,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_channel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{3}
}

func (x *ToolDefinition) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ToolDefinition) GetActionDescription() string {
	if x != nil {
		return x.ActionDescription
	}
	return ""
}

func (x *ToolDefinition) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ToolDefinition) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ToolDefinition) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ToolDefinition) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ToolDefinition) GetRequiredEnv() []string {
	if x != nil {
		return x.RequiredEnv
	}
	return nil
}

func (x *ToolDefinition) GetParameters() []*ToolParam {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ToolParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolParam) Reset() {
	*x = ToolParam{}
	mi := &file_channel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolParam) ProtoMessage() {}

func (x *ToolParam) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolParam.ProtoReflect.Descriptor instead.
func (*ToolParam) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{4}
}

func (x *ToolParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolParam) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolParam) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_channel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{5}
}

type InboundMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChannelId      string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ThreadId       string                 `protobuf:"bytes,3,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	SenderId       string                 `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderName     string                 `protobuf:"bytes,5,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Content        string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Files          []*FileAttachment      `protobuf:"bytes,7,rep,name=files,proto3" json:"files,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InboundMessage) Reset() {
	*x = InboundMessage{}
	mi := &file_channel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundMessage) ProtoMessage() {}

func (x *InboundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundMessage.ProtoReflect.Descriptor instead.
func (*InboundMessage) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{6}
}

func (x *InboundMessage) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *InboundMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *InboundMessage) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *InboundMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *InboundMessage) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *InboundMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *InboundMessage) GetFiles() []*FileAttachment {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *InboundMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InboundMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type OutboundMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ThreadId       string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Files          []*FileAttachment      `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OutboundMessage) Reset() {
	*x = OutboundMessage{}
	mi := &file_channel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundMessage) ProtoMessage() {}

func (x *OutboundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundMessage.ProtoReflect.Descriptor instead.
func (*OutboundMessage) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{7}
}

func (x *OutboundMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *OutboundMessage) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *OutboundMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *OutboundMessage) GetFiles() []*FileAttachment {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *OutboundMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FileAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileAttachment) Reset() {
	*x = FileAttachment{}
	mi := &file_channel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAttachment) ProtoMessage() {}

func (x *FileAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAttachment.ProtoReflect.Descriptor instead.
func (*FileAttachment) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{8}
}

func (x *FileAttachment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileAttachment) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileAttachment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileAttachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ChannelCapabilities struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Threads          bool                   `protobuf:"varint,3,opt,name=threads,proto3" json:"threads,omitempty"`
	Files            bool                   `protobuf:"varint,4,opt,name=files,proto3" json:"files,omitempty"`
	Reactions        bool                   `protobuf:"varint,5,opt,name=reactions,proto3" json:"reactions,omitempty"`
	Edits            bool                   `protobuf:"varint,6,opt,name=edits,proto3" json:"edits,omitempty"`
	MaxMessageLength int64                  `protobuf:"varint,7,opt,name=max_message_length,json=maxMessageLength,proto3" json:"max_message_length,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChannelCapabilities) Reset() {
	*x = ChannelCapabilities{}
	mi := &file_channel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelCapabilities) ProtoMessage() {}

func (x *ChannelCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelCapabilities.ProtoReflect.Descriptor instead.
func (*ChannelCapabilities) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{9}
}

func (x *ChannelCapabilities) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChannelCapabilities) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelCapabilities) GetThreads() bool {
	if x != nil {
		return x.Threads
	}
	return false
}

func (x *ChannelCapabilities) GetFiles() bool {
	if x != nil {
		return x.Files
	}
	return false
}

func (x *ChannelCapabilities) GetReactions() bool {
	if x != nil {
		return x.Reactions
	}
	return false
}

func (x *ChannelCapabilities) GetEdits() bool {
	if x != nil {
		return x.Edits
	}
	return false
}

func (x *ChannelCapabilities) GetMaxMessageLength() int64 {
	if x != nil {
		return x.MaxMessageLength
	}
	return 0
}

var File_channel_proto protoreflect.FileDescriptor

const file_channel_proto_rawDesc = "" +
	"\n" +
	"\rchannel.proto\x12\x14opentalon.channel.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x10ConfigureRequest\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06config\"\x13\n" +
	"\x11ConfigureResponse\"K\n" +
	"\rToolsResponse\x12:\n" +
	"\x05tools\x18\x01 \x03(\v2$.opentalon.channel.v1.ToolDefinitionR\x05tools\"\xbc\x03\n" +
	"\x0eToolDefinition\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12-\n" +
	"\x12action_description\x18\x04 \x01(\tR\x11actionDescription\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x12\n" +
	"\x04body\x18\a \x01(\tR\x04body\x12K\n" +
	"\aheaders\x18\b \x03(\v21.opentalon.channel.v1.ToolDefinition.HeadersEntryR\aheaders\x12!\n" +
	"\frequired_env\x18\t \x03(\tR\vrequiredEnv\x12?\n" +
	"\n" +
	"parameters\x18\n" +
	" \x03(\v2\x1f.opentalon.channel.v1.ToolParamR\n" +
	"parameters\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\tToolParam\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\"\x0e\n" +
	"\fSendResponse\"\xd0\x03\n" +
	"\x0eInboundMessage\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tthread_id\x18\x03 \x01(\tR\bthreadId\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vsender_name\x18\x05 \x01(\tR\n" +
	"senderName\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12:\n" +
	"\x05files\x18\a \x03(\v2$.opentalon.channel.v1.FileAttachmentR\x05files\x12N\n" +
	"\bmetadata\x18\b \x03(\v22.opentalon.channel.v1.InboundMessage.MetadataEntryR\bmetadata\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x02\n" +
	"\x0fOutboundMessage\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12:\n" +
	"\x05files\x18\x04 \x03(\v2$.opentalon.channel.v1.FileAttachmentR\x05files\x12O\n" +
	"\bmetadata\x18\x05 \x03(\v23.opentalon.channel.v1.OutboundMessage.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\x0eFileAttachment\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"\xcb\x01\n" +
	"\x13ChannelCapabilities\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\athreads\x18\x03 \x01(\bR\athreads\x12\x14\n" +
	"\x05files\x18\x04 \x01(\bR\x05files\x12\x1c\n" +
	"\treactions\x18\x05 \x01(\bR\treactions\x12\x14\n" +
	"\x05edits\x18\x06 \x01(\bR\x05edits\x12,\n" +
	"\x12max_message_length\x18\a \x01(\x03R\x10maxMessageLength2\xa3\x03\n" +
	"\x0eChannelService\x12Q\n" +
	"\fCapabilities\x12\x16.google.protobuf.Empty\x1a).opentalon.channel.v1.ChannelCapabilities\x12\\\n" +
	"\tConfigure\x12&.opentalon.channel.v1.ConfigureRequest\x1a'.opentalon.channel.v1.ConfigureResponse\x12D\n" +
	"\x05Tools\x12\x16.google.protobuf.Empty\x1a#.opentalon.channel.v1.ToolsResponse\x12G\n" +
	"\x05Start\x12\x16.google.protobuf.Empty\x1a$.opentalon.channel.v1.InboundMessage0\x01\x12Q\n" +
	"\x04Send\x12%.opentalon.channel.v1.OutboundMessage\x1a\".opentalon.channel.v1.SendResponseB6Z4github.com/opentalon/opentalon/pkg/channel/channelpbb\x06proto3"

var (
	file_channel_proto_rawDescOnce sync.Once
	file_channel_proto_rawDescData []byte
)

func file_channel_proto_rawDescGZIP() []byte {
	file_channel_proto_rawDescOnce.Do(func() {
		file_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_channel_proto_rawDesc), len(file_channel_proto_rawDesc)))
	})
	return file_channel_proto_rawDescData
}

var file_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_channel_proto_goTypes = []any{
	(*ConfigureRequest)(nil),      // 0: opentalon.channel.v1.ConfigureRequest
	(*ConfigureResponse)(nil),     // 1: opentalon.channel.v1.ConfigureResponse
	(*ToolsResponse)(nil),         // 2: opentalon.channel.v1.ToolsResponse
	(*ToolDefinition)(nil),        // 3: opentalon.channel.v1.ToolDefinition
	(*ToolParam)(nil),             // 4: opentalon.channel.v1.ToolParam
	(*SendResponse)(nil),          // 5: opentalon.channel.v1.SendResponse
	(*InboundMessage)(nil),        // 6: opentalon.channel.v1.InboundMessage
	(*OutboundMessage)(nil),       // 7: opentalon.channel.v1.OutboundMessage
	(*FileAttachment)(nil),        // 8: opentalon.channel.v1.FileAttachment
	(*ChannelCapabilities)(nil),   // 9: opentalon.channel.v1.ChannelCapabilities
	nil,                           // 10: opentalon.channel.v1.ToolDefinition.HeadersEntry
	nil,                           // 11: opentalon.channel.v1.InboundMessage.MetadataEntry
	nil,                           // 12: opentalon.channel.v1.OutboundMessage.MetadataEntry
	(*structpb.Struct)(nil),       // 13: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 15: google.protobuf.Empty
}
var file_channel_proto_depIdxs = []int32{
	13, // 0: opentalon.channel.v1.ConfigureRequest.config:type_name -> google.protobuf.Struct
	3,  // 1: opentalon.channel.v1.ToolsResponse.tools:type_name -> opentalon.channel.v1.ToolDefinition
	10, // 2: opentalon.channel.v1.ToolDefinition.headers:type_name -> opentalon.channel.v1.ToolDefinition.HeadersEntry
	4,  // 3: opentalon.channel.v1.ToolDefinition.parameters:type_name -> opentalon.channel.v1.ToolParam
	8,  // 4: opentalon.channel.v1.InboundMessage.files:type_name -> opentalon.channel.v1.FileAttachment
	11, // 5: opentalon.channel.v1.InboundMessage.metadata:type_name -> opentalon.channel.v1.InboundMessage.MetadataEntry
	14, // 6: opentalon.channel.v1.InboundMessage.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 7: opentalon.channel.v1.OutboundMessage.files:type_name -> opentalon.channel.v1.FileAttachment
	12, // 8: opentalon.channel.v1.OutboundMessage.metadata:type_name -> opentalon.channel.v1.OutboundMessage.MetadataEntry
	15, // 9: opentalon.channel.v1.ChannelService.Capabilities:input_type -> google.protobuf.Empty
	0,  // 10: opentalon.channel.v1.ChannelService.Configure:input_type -> opentalon.channel.v1.ConfigureRequest
	15, // 11: opentalon.channel.v1.ChannelService.Tools:input_type -> google.protobuf.Empty
	15, // 12: opentalon.channel.v1.ChannelService.Start:input_type -> google.protobuf.Empty
	7,  // 13: opentalon.channel.v1.ChannelService.Send:input_type -> opentalon.channel.v1.OutboundMessage
	9,  // 14: opentalon.channel.v1.ChannelService.Capabilities:output_type -> opentalon.channel.v1.ChannelCapabilities
	1,  // 15: opentalon.channel.v1.ChannelService.Configure:output_type -> opentalon.channel.v1.ConfigureResponse
	2,  // 16: opentalon.channel.v1.ChannelService.Tools:output_type -> opentalon.channel.v1.ToolsResponse
	6,  // 17: opentalon.channel.v1.ChannelService.Start:output_type -> opentalon.channel.v1.InboundMessage
	5,  // 18: opentalon.channel.v1.ChannelService.Send:output_type -> opentalon.channel.v1.SendResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_channel_proto_init() }
func file_channel_proto_init() {
	if File_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_channel_proto_rawDesc), len(file_channel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_channel_proto_goTypes,
		DependencyIndexes: file_channel_proto_depIdxs,
		MessageInfos:      file_channel_proto_msgTypes,
	}.Build()
	File_channel_proto = out.File
	file_channel_proto_goTypes = nil
	file_channel_proto_depIdxs = nil
}
