// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin.proto

package pluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HostMessage is one frame on the host → plugin direction of an
// ExecuteBidi stream. The first frame is always {call}; subsequent
// frames are {callback_response}, each correlated by id to a prior
// PluginMessage{callback_request}.
type HostMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*HostMessage_Call
	//	*HostMessage_CallbackResponse
	Payload       isHostMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostMessage) Reset() {
	*x = HostMessage{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMessage) ProtoMessage() {}

func (x *HostMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMessage.ProtoReflect.Descriptor instead.
func (*HostMessage) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *HostMessage) GetPayload() isHostMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HostMessage) GetCall() *ToolCallRequest {
	if x != nil {
		if x, ok := x.Payload.(*HostMessage_Call); ok {
			return x.Call
		}
	}
	return nil
}

func (x *HostMessage) GetCallbackResponse() *CallbackResponse {
	if x != nil {
		if x, ok := x.Payload.(*HostMessage_CallbackResponse); ok {
			return x.CallbackResponse
		}
	}
	return nil
}

type isHostMessage_Payload interface {
	isHostMessage_Payload()
}

type HostMessage_Call struct {
	Call *ToolCallRequest `protobuf:"bytes,1,opt,name=call,proto3,oneof"`
}

type HostMessage_CallbackResponse struct {
	CallbackResponse *CallbackResponse `protobuf:"bytes,2,opt,name=callback_response,json=callbackResponse,proto3,oneof"`
}

func (*HostMessage_Call) isHostMessage_Payload() {}

func (*HostMessage_CallbackResponse) isHostMessage_Payload() {}

// PluginMessage is one frame on the plugin → host direction of an
// ExecuteBidi stream. Frames are zero or more {callback_request}
// (each requesting a host-side RunAction) followed by exactly one
// terminal {result}; sending {result} closes the plugin's send half.
type PluginMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PluginMessage_CallbackRequest
	//	*PluginMessage_Result
	Payload       isPluginMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginMessage) Reset() {
	*x = PluginMessage{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMessage) ProtoMessage() {}

func (x *PluginMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMessage.ProtoReflect.Descriptor instead.
func (*PluginMessage) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginMessage) GetPayload() isPluginMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PluginMessage) GetCallbackRequest() *CallbackRequest {
	if x != nil {
		if x, ok := x.Payload.(*PluginMessage_CallbackRequest); ok {
			return x.CallbackRequest
		}
	}
	return nil
}

func (x *PluginMessage) GetResult() *ToolResultResponse {
	if x != nil {
		if x, ok := x.Payload.(*PluginMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isPluginMessage_Payload interface {
	isPluginMessage_Payload()
}

type PluginMessage_CallbackRequest struct {
	CallbackRequest *CallbackRequest `protobuf:"bytes,1,opt,name=callback_request,json=callbackRequest,proto3,oneof"`
}

type PluginMessage_Result struct {
	Result *ToolResultResponse `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*PluginMessage_CallbackRequest) isPluginMessage_Payload() {}

func (*PluginMessage_Result) isPluginMessage_Payload() {}

// CallbackRequest asks the host to invoke another tool/action via its
// normal executeCall path. The host's profile/actor context for the
// dispatched call is inherited from the surrounding ToolCallRequest's
// context — no identity fields needed on the wire, because the host
// already knows who is talking to this plugin process.
type CallbackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id correlates with the CallbackResponse the host returns. Plugins
	// may have multiple callbacks outstanding (host responses are not
	// guaranteed to arrive in request order); the id keeps them matched.
	Id            string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Plugin        string            `protobuf:"bytes,2,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Action        string            `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Args          map[string]string `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackRequest) Reset() {
	*x = CallbackRequest{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackRequest) ProtoMessage() {}

func (x *CallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackRequest.ProtoReflect.Descriptor instead.
func (*CallbackRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *CallbackRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CallbackRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *CallbackRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CallbackRequest) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

// CallbackResponse is the host's reply to one CallbackRequest. id
// matches the request's id. Either content or error is set.
type CallbackResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content           string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Error             string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	StructuredContent string                 `protobuf:"bytes,4,opt,name=structured_content,json=structuredContent,proto3" json:"structured_content,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CallbackResponse) Reset() {
	*x = CallbackResponse{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackResponse) ProtoMessage() {}

func (x *CallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackResponse.ProtoReflect.Descriptor instead.
func (*CallbackResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *CallbackResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CallbackResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CallbackResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CallbackResponse) GetStructuredContent() string {
	if x != nil {
		return x.StructuredContent
	}
	return ""
}

type PluginInitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInitRequest) Reset() {
	*x = PluginInitRequest{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInitRequest) ProtoMessage() {}

func (x *PluginInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInitRequest.ProtoReflect.Descriptor instead.
func (*PluginInitRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *PluginInitRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type ToolCallRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Plugin string                 `protobuf:"bytes,2,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Action string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Args   map[string]string      `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Per-request credential headers from the verified profile, keyed by MCP server name.
	// Each entry specifies an HTTP header name and value to inject when calling that server.
	// Example: {"myapp": {header: "X-App-User", value: "123"}}.
	// The plugin merges these with its static configured headers; credential headers take priority.
	CredentialHeaders map[string]*CredentialHeader `protobuf:"bytes,6,rep,name=credential_headers,json=credentialHeaders,proto3" json:"credential_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ToolCallRequest) Reset() {
	*x = ToolCallRequest{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallRequest) ProtoMessage() {}

func (x *ToolCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallRequest.ProtoReflect.Descriptor instead.
func (*ToolCallRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ToolCallRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCallRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *ToolCallRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ToolCallRequest) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ToolCallRequest) GetCredentialHeaders() map[string]*CredentialHeader {
	if x != nil {
		return x.CredentialHeaders
	}
	return nil
}

// CredentialHeader is a per-MCP-server credential specifying an HTTP header
// name and value to inject into requests to that server.
type CredentialHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        string                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // HTTP header name (e.g. "X-App-User", "Authorization")
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`   // header value (e.g. "user-123", "Bearer tok")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialHeader) Reset() {
	*x = CredentialHeader{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialHeader) ProtoMessage() {}

func (x *CredentialHeader) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialHeader.ProtoReflect.Descriptor instead.
func (*CredentialHeader) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *CredentialHeader) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *CredentialHeader) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ToolResultResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	CallId  string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Content string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Error   string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Optional structured payload from the underlying tool. Mirrors the
	// `structuredContent` field defined by the MCP spec (revision 2025-06+):
	// when a tool emits both a human-readable text block (`content`) and a
	// schema-validated JSON record, the latter goes here so the host can
	// render or forward it as a separate channel without relying on string
	// delimiters embedded in `content`. JSON-encoded; empty when omitted.
	StructuredContent string `protobuf:"bytes,4,opt,name=structured_content,json=structuredContent,proto3" json:"structured_content,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ToolResultResponse) Reset() {
	*x = ToolResultResponse{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultResponse) ProtoMessage() {}

func (x *ToolResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResultResponse.ProtoReflect.Descriptor instead.
func (*ToolResultResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ToolResultResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolResultResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ToolResultResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ToolResultResponse) GetStructuredContent() string {
	if x != nil {
		return x.StructuredContent
	}
	return ""
}

type PluginCapabilities struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Actions     []*Action              `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	// Optional text injected into the LLM system prompt when this plugin is loaded.
	// Use it to surface context the LLM should know about (e.g. API base URLs, capability notes).
	//
	// Security: plugins are currently trusted subprocesses (operator-installed, same host).
	// If plugin trust is ever relaxed (e.g. third-party marketplace), this field becomes a
	// prompt-injection vector and must be sanitised or sandboxed before inclusion.
	SystemPromptAddition string `protobuf:"bytes,4,opt,name=system_prompt_addition,json=systemPromptAddition,proto3" json:"system_prompt_addition,omitempty"`
	// Optional glossary entries provided by the plugin (e.g. from an MCP server).
	// The orchestrator collects entries from all plugins and syncs them to the
	// vector store via the sync_glossary action for automatic context injection.
	Glossary []*GlossaryEntry `protobuf:"bytes,5,rep,name=glossary,proto3" json:"glossary,omitempty"`
	// Optional per-section knowledge articles provided by the plugin (e.g. an
	// MCP server's `initialize._meta.knowledge_articles`). Each entry becomes
	// one KnowledgeArticles record on the vector store with source
	// "mcp-knowledge:<plugin>:<id>" so the prepare-path RAG can pull just
	// the relevant section into [knowledge_context], instead of having the
	// whole prose go into every system prompt via system_prompt_addition.
	KnowledgeArticles []*KnowledgeArticle `protobuf:"bytes,6,rep,name=knowledge_articles,json=knowledgeArticles,proto3" json:"knowledge_articles,omitempty"`
	// SupportsCallbacks declares that this plugin needs the host to
	// dispatch its actions over ExecuteBidi (bidirectional streaming)
	// rather than the unary Execute, so it can fire CallbackRequest
	// messages mid-execution to invoke other tools/actions through the
	// host's orchestrator. Plugins that don't need that capability leave
	// this false (the default) and continue to receive unary Execute
	// traffic — no behaviour change for existing plugins.
	SupportsCallbacks bool `protobuf:"varint,7,opt,name=supports_callbacks,json=supportsCallbacks,proto3" json:"supports_callbacks,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PluginCapabilities) Reset() {
	*x = PluginCapabilities{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginCapabilities) ProtoMessage() {}

func (x *PluginCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginCapabilities.ProtoReflect.Descriptor instead.
func (*PluginCapabilities) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *PluginCapabilities) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginCapabilities) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginCapabilities) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *PluginCapabilities) GetSystemPromptAddition() string {
	if x != nil {
		return x.SystemPromptAddition
	}
	return ""
}

func (x *PluginCapabilities) GetGlossary() []*GlossaryEntry {
	if x != nil {
		return x.Glossary
	}
	return nil
}

func (x *PluginCapabilities) GetKnowledgeArticles() []*KnowledgeArticle {
	if x != nil {
		return x.KnowledgeArticles
	}
	return nil
}

func (x *PluginCapabilities) GetSupportsCallbacks() bool {
	if x != nil {
		return x.SupportsCallbacks
	}
	return false
}

type GlossaryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          string                 `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	Definition    string                 `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"` // optional grouping (e.g. "hr", "support")
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`         // optional free-form tags
	Synonyms      []string               `protobuf:"bytes,5,rep,name=synonyms,proto3" json:"synonyms,omitempty"` // alternative terms for better vector matching
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlossaryEntry) Reset() {
	*x = GlossaryEntry{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlossaryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlossaryEntry) ProtoMessage() {}

func (x *GlossaryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlossaryEntry.ProtoReflect.Descriptor instead.
func (*GlossaryEntry) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *GlossaryEntry) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *GlossaryEntry) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *GlossaryEntry) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GlossaryEntry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GlossaryEntry) GetSynonyms() []string {
	if x != nil {
		return x.Synonyms
	}
	return nil
}

// KnowledgeArticle is one self-contained reference section a plugin
// contributes for retrieval-time injection (as opposed to always-on
// inclusion via system_prompt_addition). Required fields: id, title, content.
type KnowledgeArticle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"` // optional free-form tags merged with the auto-set ["opentalon", "mcp", "knowledge", <plugin>] on storage
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeArticle) Reset() {
	*x = KnowledgeArticle{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeArticle) ProtoMessage() {}

func (x *KnowledgeArticle) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeArticle.ProtoReflect.Descriptor instead.
func (*KnowledgeArticle) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *KnowledgeArticle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KnowledgeArticle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *KnowledgeArticle) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *KnowledgeArticle) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Action struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters        []*Parameter           `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	UserOnly          bool                   `protobuf:"varint,4,opt,name=user_only,json=userOnly,proto3" json:"user_only,omitempty"`                             // if true, hidden from LLM and blocked from LLM-sourced calls; only invocable directly by the user
	InjectContextArgs []string               `protobuf:"bytes,5,rep,name=inject_context_args,json=injectContextArgs,proto3" json:"inject_context_args,omitempty"` // context arg names (e.g. "actor_id") the host injects from request context before calling Execute
	// RFC #249 Phase 4 tool-tier flag: if true, the orchestrator pins this
	// action into Tier 0 (always present in the LLM's `tools` array, full
	// schema). RAG-derived scores still feed into the per-turn ranking for
	// event diagnostics, but never demote an always_include action below
	// Tier 0. Use for capabilities a plugin considers non-negotiable for
	// its domain (e.g. an emergency-stop or session-reset action).
	AlwaysInclude bool `protobuf:"varint,6,opt,name=always_include,json=alwaysInclude,proto3" json:"always_include,omitempty"`
	// If true, the action is a pure query — it does not mutate any state
	// the user cares about. The orchestrator's per-tool-call confirmation
	// gate short-circuits when this is set: read_only=true actions execute
	// without prompting the user "I'm about to execute X, proceed?",
	// which would otherwise be noise and burn an LLM round-trip for a
	// narration that the user never needed to see. Default false — every
	// action is treated as a potential write until the plugin declares
	// otherwise. Plugins that aggregate upstream tools (e.g. the
	// mcp-plugin) typically propagate this from the upstream protocol's
	// own read-only hint (MCP: `annotations.readOnlyHint`).
	ReadOnly      bool `protobuf:"varint,7,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *Action) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Action) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Action) GetParameters() []*Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Action) GetUserOnly() bool {
	if x != nil {
		return x.UserOnly
	}
	return false
}

func (x *Action) GetInjectContextArgs() []string {
	if x != nil {
		return x.InjectContextArgs
	}
	return nil
}

func (x *Action) GetAlwaysInclude() bool {
	if x != nil {
		return x.AlwaysInclude
	}
	return false
}

func (x *Action) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type Parameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *Parameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Parameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Parameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Parameter) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x13opentalon.plugin.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xaa\x01\n" +
	"\vHostMessage\x12:\n" +
	"\x04call\x18\x01 \x01(\v2$.opentalon.plugin.v1.ToolCallRequestH\x00R\x04call\x12T\n" +
	"\x11callback_response\x18\x02 \x01(\v2%.opentalon.plugin.v1.CallbackResponseH\x00R\x10callbackResponseB\t\n" +
	"\apayload\"\xb0\x01\n" +
	"\rPluginMessage\x12Q\n" +
	"\x10callback_request\x18\x01 \x01(\v2$.opentalon.plugin.v1.CallbackRequestH\x00R\x0fcallbackRequest\x12A\n" +
	"\x06result\x18\x02 \x01(\v2'.opentalon.plugin.v1.ToolResultResponseH\x00R\x06resultB\t\n" +
	"\apayload\"\xce\x01\n" +
	"\x0fCallbackRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06plugin\x18\x02 \x01(\tR\x06plugin\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12B\n" +
	"\x04args\x18\x04 \x03(\v2..opentalon.plugin.v1.CallbackRequest.ArgsEntryR\x04args\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x01\n" +
	"\x10CallbackResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12-\n" +
	"\x12structured_content\x18\x04 \x01(\tR\x11structuredContent\"4\n" +
	"\x11PluginInitRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\"\xad\x03\n" +
	"\x0fToolCallRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06plugin\x18\x02 \x01(\tR\x06plugin\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12B\n" +
	"\x04args\x18\x04 \x03(\v2..opentalon.plugin.v1.ToolCallRequest.ArgsEntryR\x04args\x12j\n" +
	"\x12credential_headers\x18\x06 \x03(\v2;.opentalon.plugin.v1.ToolCallRequest.CredentialHeadersEntryR\x11credentialHeaders\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1ak\n" +
	"\x16CredentialHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.opentalon.plugin.v1.CredentialHeaderR\x05value:\x028\x01J\x04\b\x05\x10\x06\"@\n" +
	"\x10CredentialHeader\x12\x16\n" +
	"\x06header\x18\x01 \x01(\tR\x06header\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x8c\x01\n" +
	"\x12ToolResultResponse\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12-\n" +
	"\x12structured_content\x18\x04 \x01(\tR\x11structuredContent\"\xfc\x02\n" +
	"\x12PluginCapabilities\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x125\n" +
	"\aactions\x18\x03 \x03(\v2\x1b.opentalon.plugin.v1.ActionR\aactions\x124\n" +
	"\x16system_prompt_addition\x18\x04 \x01(\tR\x14systemPromptAddition\x12>\n" +
	"\bglossary\x18\x05 \x03(\v2\".opentalon.plugin.v1.GlossaryEntryR\bglossary\x12T\n" +
	"\x12knowledge_articles\x18\x06 \x03(\v2%.opentalon.plugin.v1.KnowledgeArticleR\x11knowledgeArticles\x12-\n" +
	"\x12supports_callbacks\x18\a \x01(\bR\x11supportsCallbacks\"\x8f\x01\n" +
	"\rGlossaryEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\tR\x04term\x12\x1e\n" +
	"\n" +
	"definition\x18\x02 \x01(\tR\n" +
	"definition\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1a\n" +
	"\bsynonyms\x18\x05 \x03(\tR\bsynonyms\"f\n" +
	"\x10KnowledgeArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"\x8f\x02\n" +
	"\x06Action\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12>\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2\x1e.opentalon.plugin.v1.ParameterR\n" +
	"parameters\x12\x1b\n" +
	"\tuser_only\x18\x04 \x01(\bR\buserOnly\x12.\n" +
	"\x13inject_context_args\x18\x05 \x03(\tR\x11injectContextArgs\x12%\n" +
	"\x0ealways_include\x18\x06 \x01(\bR\ralwaysInclude\x12\x1b\n" +
	"\tread_only\x18\a \x01(\bR\breadOnly\"q\n" +
	"\tParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired2\xdb\x02\n" +
	"\rPluginService\x12F\n" +
	"\x04Init\x12&.opentalon.plugin.v1.PluginInitRequest\x1a\x16.google.protobuf.Empty\x12X\n" +
	"\aExecute\x12$.opentalon.plugin.v1.ToolCallRequest\x1a'.opentalon.plugin.v1.ToolResultResponse\x12O\n" +
	"\fCapabilities\x12\x16.google.protobuf.Empty\x1a'.opentalon.plugin.v1.PluginCapabilities\x12W\n" +
	"\vExecuteBidi\x12 .opentalon.plugin.v1.HostMessage\x1a\".opentalon.plugin.v1.PluginMessage(\x010\x01B/Z-github.com/opentalon/opentalon/proto/pluginpbb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_plugin_proto_goTypes = []any{
	(*HostMessage)(nil),        // 0: opentalon.plugin.v1.HostMessage
	(*PluginMessage)(nil),      // 1: opentalon.plugin.v1.PluginMessage
	(*CallbackRequest)(nil),    // 2: opentalon.plugin.v1.CallbackRequest
	(*CallbackResponse)(nil),   // 3: opentalon.plugin.v1.CallbackResponse
	(*PluginInitRequest)(nil),  // 4: opentalon.plugin.v1.PluginInitRequest
	(*ToolCallRequest)(nil),    // 5: opentalon.plugin.v1.ToolCallRequest
	(*CredentialHeader)(nil),   // 6: opentalon.plugin.v1.CredentialHeader
	(*ToolResultResponse)(nil), // 7: opentalon.plugin.v1.ToolResultResponse
	(*PluginCapabilities)(nil), // 8: opentalon.plugin.v1.PluginCapabilities
	(*GlossaryEntry)(nil),      // 9: opentalon.plugin.v1.GlossaryEntry
	(*KnowledgeArticle)(nil),   // 10: opentalon.plugin.v1.KnowledgeArticle
	(*Action)(nil),             // 11: opentalon.plugin.v1.Action
	(*Parameter)(nil),          // 12: opentalon.plugin.v1.Parameter
	nil,                        // 13: opentalon.plugin.v1.CallbackRequest.ArgsEntry
	nil,                        // 14: opentalon.plugin.v1.ToolCallRequest.ArgsEntry
	nil,                        // 15: opentalon.plugin.v1.ToolCallRequest.CredentialHeadersEntry
	(*emptypb.Empty)(nil),      // 16: google.protobuf.Empty
}
var file_plugin_proto_depIdxs = []int32{
	5,  // 0: opentalon.plugin.v1.HostMessage.call:type_name -> opentalon.plugin.v1.ToolCallRequest
	3,  // 1: opentalon.plugin.v1.HostMessage.callback_response:type_name -> opentalon.plugin.v1.CallbackResponse
	2,  // 2: opentalon.plugin.v1.PluginMessage.callback_request:type_name -> opentalon.plugin.v1.CallbackRequest
	7,  // 3: opentalon.plugin.v1.PluginMessage.result:type_name -> opentalon.plugin.v1.ToolResultResponse
	13, // 4: opentalon.plugin.v1.CallbackRequest.args:type_name -> opentalon.plugin.v1.CallbackRequest.ArgsEntry
	14, // 5: opentalon.plugin.v1.ToolCallRequest.args:type_name -> opentalon.plugin.v1.ToolCallRequest.ArgsEntry
	15, // 6: opentalon.plugin.v1.ToolCallRequest.credential_headers:type_name -> opentalon.plugin.v1.ToolCallRequest.CredentialHeadersEntry
	11, // 7: opentalon.plugin.v1.PluginCapabilities.actions:type_name -> opentalon.plugin.v1.Action
	9,  // 8: opentalon.plugin.v1.PluginCapabilities.glossary:type_name -> opentalon.plugin.v1.GlossaryEntry
	10, // 9: opentalon.plugin.v1.PluginCapabilities.knowledge_articles:type_name -> opentalon.plugin.v1.KnowledgeArticle
	12, // 10: opentalon.plugin.v1.Action.parameters:type_name -> opentalon.plugin.v1.Parameter
	6,  // 11: opentalon.plugin.v1.ToolCallRequest.CredentialHeadersEntry.value:type_name -> opentalon.plugin.v1.CredentialHeader
	4,  // 12: opentalon.plugin.v1.PluginService.Init:input_type -> opentalon.plugin.v1.PluginInitRequest
	5,  // 13: opentalon.plugin.v1.PluginService.Execute:input_type -> opentalon.plugin.v1.ToolCallRequest
	16, // 14: opentalon.plugin.v1.PluginService.Capabilities:input_type -> google.protobuf.Empty
	0,  // 15: opentalon.plugin.v1.PluginService.ExecuteBidi:input_type -> opentalon.plugin.v1.HostMessage
	16, // 16: opentalon.plugin.v1.PluginService.Init:output_type -> google.protobuf.Empty
	7,  // 17: opentalon.plugin.v1.PluginService.Execute:output_type -> opentalon.plugin.v1.ToolResultResponse
	8,  // 18: opentalon.plugin.v1.PluginService.Capabilities:output_type -> opentalon.plugin.v1.PluginCapabilities
	1,  // 19: opentalon.plugin.v1.PluginService.ExecuteBidi:output_type -> opentalon.plugin.v1.PluginMessage
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	file_plugin_proto_msgTypes[0].OneofWrappers = []any{
		(*HostMessage_Call)(nil),
		(*HostMessage_CallbackResponse)(nil),
	}
	file_plugin_proto_msgTypes[1].OneofWrappers = []any{
		(*PluginMessage_CallbackRequest)(nil),
		(*PluginMessage_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
